### ISSUE TITLE
I started forked project!

### ISSUE THREAD

**Issue by ubugeeei** [asdfjkl/kanjicanvas#11]
@asdfjkl 

Hello. Thank you for the wonderful project.
I love this project.

For use in various projects, I've published a forked version of the project as an alpha version.
https://github.com/Ubugeeei/tecack
https://ubugeeei.github.io/tecack

The objectives of this project are:

- To make it installable via npm
- Package each functionality individually
- TypeScript support
- Set up an environment for creating character data
- Comprehensive documentation
- Easier setup

KanjiCanvas is released under the MIT license, but I would like to confirm that there are no licensing issues just to be safe.

If there is an issue, I will immediately take it down. What do you think?

I reached out through an issue because the discussion was not open.

**Comment by asdfjkl** [comment]
KanjiCanvas is licensed under MIT (with required backlink); you are welcome to use it!
Of course I would appreciate if you would notifiy/push-back if you add more kanji or improve recognition.

**Comment by ubugeeei** [comment]
@asdfjkl 

Thanks!

Regarding the backlinks, are the ones mentioned in the documentation and README sufficient?
If there are missing parts, I will add them.
https://github.com/Ubugeeei/tecack#readme
https://ubugeeei.github.io/tecack/introduction/what-is-tecack.html#what-is-tecack

**Comment by asdfjkl** [comment]
The way you currently have set things up is perfectly fine with me, thanks!

**Comment by ubugeeei** [comment]
Thank you kindly for everything.
This issue closes!

**Comment by ubugeeei** [comment]
moved org: https://github.com/ublib/tecack
