### ISSUE TITLE
Hide stroke order on recognize

### ISSUE THREAD

**Issue by cherfaoui-syphax** [asdfjkl/kanjicanvas#13]
Is there a way to run a recognition without updating the canvas to display the stroke order ?

**Comment by kerryconvery** [comment]
What is it exactly you are trying to achieve by not having the canvas update after recognition?  Is it that you don't want the stroke order displayed or something else?

**Comment by cherfaoui-syphax** [comment]
> What is it exactly you are trying to achieve by not having the canvas update after recognition? Is it that you don't want the stroke order displayed or something else?

What I'm trying to achieve is to run the recognition function each time a new stroke is drawn, but I don't want the stroke order to be displayed after each recognition. Ideally, I'd like to control when the stroke order is shown or hidden with a separate function. It would also be really helpful if the canvas could call a callback function after each new stroke. For now, though, I can manage this using mousedown and mouseup event listeners.
something like 
KanjiCanvas.showStrokeOrder("canvas") / KanjiCanvas.hideStrokeOrder("canvas")
KanjiCanvas.onNewStroke = myFunction

**Comment by SethClydesdale** [comment]
Hello, @cherfaoui-syphax!

It's been a little while since I worked on this, but if I recall correctly, `redraw` is the function that's called on each recognition to display the stroke order. In the unminimized script, find `KanjiCanvas.recognize` and replace it with the following:
```javascript
    KanjiCanvas.recognize = function (id, redraw) {
      var mn = KanjiCanvas.momentNormalize(id);

      var extractedFeatures = KanjiCanvas.extractFeatures(mn, 20.);

      var map = KanjiCanvas.getMap(extractedFeatures, KanjiCanvas.refPatterns[0][2] ,KanjiCanvas.endPointDistance);
      map = KanjiCanvas.completeMap(extractedFeatures, KanjiCanvas.refPatterns[0][2],KanjiCanvas.endPointDistance, map);

      var candidates = KanjiCanvas.coarseClassification(extractedFeatures);

      if (redraw) KanjiCanvas.redraw(id);

      // display candidates in the specified element
      if (KanjiCanvas["canvas_" + id].dataset.candidateList) {
        document.getElementById(KanjiCanvas["canvas_" + id].dataset.candidateList).innerHTML = KanjiCanvas.fineClassification(extractedFeatures, candidates);
      } 

      // otherwise log the result to the console if no candidateList is specified
      else {
        return KanjiCanvas.fineClassification(extractedFeatures, candidates);
      }
    };
```
This will disable redraw by default, unless you pass `true` to the second argument like so: `KanjiCanvas.recognize(ID, true)`

As for toggling the stroke order display, you can add in this function (which is a repurposed version of the undo function):
```javascript
  KanjiCanvas.clearOrder = function (id) {
    KanjiCanvas["ctx_" + id].clearRect(0, 0, KanjiCanvas["w_" + id], KanjiCanvas["h_" + id]);
    for(var i = 0; i<KanjiCanvas["recordedPattern_" + id].length; i++) {
      var stroke_i = KanjiCanvas["recordedPattern_" + id][i];
      for(var j = 0; j<stroke_i.length-1;j++) {
        KanjiCanvas["prevX_" + id] = stroke_i[j][0];
        KanjiCanvas["prevY_" + id] = stroke_i[j][1];

        KanjiCanvas["currX_" + id] = stroke_i[j+1][0];
        KanjiCanvas["currY_" + id] = stroke_i[j+1][1];
        KanjiCanvas.draw(id);
      }
    }
  };
```
Then you can call `KanjiCanvas.clearOrder(ID)` to hide the stroke order and `KanjiCanvas.redraw(ID)` to show the stroke order.
