### ISSUE TITLE
How to make it work with hiragana letters?

### ISSUE THREAD

**Issue by Alii-isk** [asdfjkl/kanjicanvas#5]
first I really love this repo you did a really good job.😊❤
i testing this and i want to know if there is a way to make i work with Japanese hiragana characters?😄

**Comment by asdfjkl** [comment]
Yes - if someone adds patterns for hiragana and/or katakana.

However the recognition preformance is not that great - it's usually in the top 10, but not one of the first hits. The reason is that there are few strokes and therefore not a lot of features for comparison.

Because of that and since hiragana/katakana are easy to learn, they are currently not included.

**Comment by Alii-isk** [comment]
so less strokes means less features which leads to low recognition performance got it 👍
Do you thinks there is another way to recognize hiragana that can work on the web

**Comment by asdfjkl** [comment]
I mean you can give it a try. There is a tutorial on how to add patterns; it's actually not that difficult.

W.r.t. to other ways of recognitiom: Doing this full-client side, I do not see other possibilities. Among those "old-school" pattern recognition methods, this seems to be the most powerful.
If you do stuff with a server-backend, then there are plenty of possibilities. The best is probably training a deep neural network, submitting the canvas with something like ajax, and then reporting everything back. Similar to this https://github.com/CaptainDario/DaKanji-ML
Then there is the question of the license of the character data for training the neural network, of course...

**Comment by Alii-isk** [comment]
**Thank you** , you are very helpful 
Currently I don't wanna deal with **deep neural network**, so I am going to try to make a hiragana patterns and test it out

**Comment by SethClydesdale** [comment]
Hi @Alii-isk, 

I don't know if you still require it, but I have some ref patterns for hiragana and katakana + their diacritics. You can find them in my repository for Genki:
https://github.com/SethClydesdale/genki-study-resources/tree/master/resources/javascript/ref-patterns

I recall adjusting the hiragana/katakana patterns to work with the fonts used [here](https://sethclydesdale.github.io/genki-study-resources/lessons-3rd/lesson-1/literacy-wb-1/?start=1). Though I cannot recall if I made any adjustments to the diacritical patterns. Hopefully they help you, or someone else out looking for similar patterns.

**Comment by Alii-isk** [comment]
> Hi @Alii-isk,
> 
> I don't know if you still require it, but I have some ref patterns for hiragana and katakana + their diacritics. You can find them in my repository for Genki:
> https://github.com/SethClydesdale/genki-study-resources/tree/master/resources/javascript/ref-patterns
> 
> I recall adjusting the hiragana/katakana patterns to work with the fonts used [here](https://sethclydesdale.github.io/genki-study-resources/lessons-3rd/lesson-1/literacy-wb-1/?start=1). Though I cannot recall if I made any adjustments to the diacritical patterns. Hopefully they help you, or someone else out looking for similar patterns.

woow thannnk you a lot😊😊😋😋😁😁😁😍

**Comment by ghost** [comment]
Hi Can I use your kanji stroke in my website and this is for japanese language leraners

**Comment by asdfjkl** [comment]
As long as you adhere to the MIT license, yes, you can use it on your own website.
