### ISSUE TITLE
Missing Kanji

### ISSUE THREAD

**Issue by bausshf** [asdfjkl/kanjicanvas#6]
Below is a list of missing kanji that would be really useful to include as they're part of the dataset used in RTK.

I couldn't find them in the ref patterns at least.

I think they should be supported by default.

Other than those few missing kanji, super great project and I really enjoy it.

```
吾
朋
昌
旭
亘
只
頁
肌
勺
汐
砂
填
圭
鯉
林
桂
柏
梢
杏
桐
沫
荻
王
銑
辻
敬
幌
嬌
匕
蝶
独
進
曰
描
掲
乃
允
裳
敢
徳
街
数
笠
笹
篭
匁
勿
伊
漕
散
廿
之
智
弘
猪
渚
阿
窪
苑
酉
梓
摯
菱
亥
椿
錘
栗
楠
枢
彦
亜
蒲
航
瓜
函
脹
烏
蔦
鳩
薦
寅
辰
丑
卯
巳
```

**Comment by christopherball** [comment]
On a similar but related note, based on my analysis, `data.txt` includes 2,127 kanji characters, 12 of which aren't members of the standard use 常用漢字 set, thus the tool currently offers 2,115 / 2,136 standard use kanji.  That's unfortunate, as this is otherwise great!

**Comment by asdfjkl** [comment]
I've added the above missing list of kanji in 0fa344f92ef737b689bf75fe3f51d214526b50d6
There are now 2206 kanji. 

Todo: The following Jouyou kanji are still missing:

供
自
𠮟
小
夕
剝
彼
服
頰

**Comment by asdfjkl** [comment]
added remaining jouyou kanji except 
𠮟 [U+20B9F]
Before the jouyou reform 2010 there was actually 
叱 [U+53F1]

U+20B9F is the only jouyou kanji that maps to extension B of Unicode thus requiring 5 hex digits, all others map to the main block (4 hex digits). In any way it's unclear what the user expects when he looks up a kanji (two results? one result, if so which one?). As 𠮟 is still used often, we will stick for that (older) one for now.

**Comment by christopherball** [comment]
Nice!  I was planning on getting around to this myself (had already installed the latest JRE and tinkered with the jTegaki utility).  Will give things a spin in a bit.  Thanks for completing the kanji set :).
